spring.application.name=AtelieGarnie
//conexão com postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/AtelieGarnie 
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
// Configuração do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
// Configuração do flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

